services:
  web_app:
    image: ghcr.io/engineering-research-and-development/synthetic-data-generator:middleware
    ports:
      - "80:8001"
  postgres_database:
    image: "postgres"
    ports:
      - "2022:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"