services:
  sdg-middleware:
    image: ghcr.io/engineering-research-and-development/synthetic-data-generator:middleware
    ports:
      - "8001:8001"
    environment:
      db_host: "database"
      db_name: "postgres"
      db_password: "postgres"
      db_username: "postgres"
      RELOAD_DATABASE: True
    depends_on:
      - database
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"