package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"gqlServer/graph/model"
)

// Behaviours is the resolver for the behaviours field.
func (r *queryResolver) Behaviours(ctx context.Context) ([]*model.Behaviour, error) {
	var behaviours []*model.Behaviour
	if err := r.DB.Preload("FunctionParameters").Find(&behaviours).Error; err != nil {
		return nil, err
	}
	return behaviours, nil
}

// Behaviour is the resolver for the behaviour field.
func (r *queryResolver) Behaviour(ctx context.Context, id int32) (*model.Behaviour, error) {
	var behaviour model.Behaviour
	if err := r.DB.Preload("FunctionParameters").First(&behaviour, id).Error; err != nil {
		return nil, err
	}
	return &behaviour, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
