---
remote_database_credentials:
  host: "postgres_database"
  database: "postgres"
  username: "postgres"
  password: "postgres"
local_database_credentials:
  host: "localhost"
  database: "modelregistry"
  username: "postgres"
  password: "admin"
...
