name: SonarQube Analysis

on:
  schedule:
    - cron: "0 4 * * 1-5"  # Runs at 4 AM UTC (Monday-Friday)
  push:
    branches:
      - "**"  # Runs on all branches
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Tailscale Docker container
        run: |
            docker run -d \
              -e TS_AUTH_ONCE=True \  
              -e TS_AUTHKEY=${{ secrets.TAILSCALE_AUTHKEY }} \
              tailscale/tailscale:latest \
              --name tailscale

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SonarQube Scan
        env:
          SONAR_HOST_URL: "http://100.117.166.97:9000"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip -d $HOME/
          export PATH=$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH
          sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

      - name: Ensure Tailscale is removed (Always)
        if: always()  # Ensures this step runs regardless of success or failure
        run: |
          docker stop tailscale
          docker rm tailscale