name: SonarQube Analysis Generator

on:
  schedule:
    - cron: "0 5 * * 1-5"  # Runs at 5 AM UTC (Monday-Friday)
  push:
    branches:
      - "**"

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ngrok Docker container
        run: |
          docker run -d --rm --name ngrok \
            -e NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            -e NGROK_PORT=9000 \
            -p 4040:4040 \
            ngrok/ngrok:latest http 9000

      - name: Wait for ngrok to start
        run: |
          sleep 5
          NGROK_URL=$(docker exec ngrok curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.NGROK_URL }}
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.NGROK_URL }}